.build:
  image: $CI_REGISTRY/$CI_PROJECT_PATH/$SG_CI_IMAGE_NAME
  stage: build 1
  tags:
    - stackgres-runner-v2
    - stackgres-maven-runner
    - linux-amd64
  script:
    - |
      sh stackgres-k8s/ci/build/build-gitlab.sh build \
        --copy stackgres-k8s/ci/build/target/junit-build.hashes.xml \
        --copy .m2 \
        --extract restapi-java:'stackgres-k8s/src/api-web/target/swagger*' \
        parent-java operator-framework-java \
        test-util-java common-java \
        operator-java restapi-java jobs-java \
        cluster-controller-java distributedlogs-controller-java
      MAVEN_OPTS='
        -Dhttps.protocols=TLSv1.2
        -Dorg.slf4j.simpleLogger.showDateTime=true
        -Djava.awt.headless=true
        -XX:+UseParallelGC
        '
      MAVEN_CLI_OPTS='
        --batch-mode
        --errors
        --show-version
        -Dmaven.repo.local=/project/.m2/repository
        -Dmaven.user.home=/project/.m2
        -DinstallAtEnd=true
        -DdeployAtEnd=true
        -Dsurefire.useFile=false
        -DtrimStackTrace=false
        '
      sh stackgres-k8s/src/mvnw $MAVEN_CLI_OPTS install -P safer -f "stackgres-k8s/src/pom.xml"
  retry:
    max: 2
    when: [ unknown_failure, api_failure, stuck_or_timeout_failure, runner_system_failure, runner_unsupported,
     stale_schedule, job_execution_timeout, archived_failure, unmet_prerequisites, scheduler_failure, data_integrity_failure ] 
  cache:
    - key:
        files:
          - stackgres-k8s/src/pom.xml
      paths:
        - .m2/
  artifacts:
    expire_in: 1 week
    when: always
    reports:
      junit:
        - stackgres-k8s/ci/build/target/junit-build.hashes.xml
        - stackgres-k8s/src/*/target/surefire-reports/TEST-*.xml
    paths:
        - stackgres-k8s/ci/build/target/*
        - stackgres-k8s/src/api-web/target/swagger*
        - stackgres-k8s/ci/build/target

build amd64:
  extends: .build
  tags:
    - stackgres-runner-v2
    - stackgres-maven-runner
    - linux-amd64

build arm64:
  extends: .build
  tags:
    - stackgres-runner-v2
    - stackgres-maven-runner
    - linux-arm64
  only:
    variables:
      - $SKIP_ARM != "true" && $CI_COMMIT_TAG && $CI_COMMIT_TAG !~ /^latest-.*$/
      - $DO_ARM

.build ui:
  image: $CI_REGISTRY/$CI_PROJECT_PATH/$SG_CI_IMAGE_NAME
  stage: build 2
  tags:
    - stackgres-runner
  script:
    - |
      sh stackgres-k8s/ci/build/build-gitlab.sh build \
        --copy stackgres-k8s/src/admin-ui/node_modules \
        admin-ui
  retry: 2
  cache:
    - key: node
      paths:
      - stackgres-k8s/src/admin-ui/node_modules

build ui amd64:
  extends: .build ui
  dependencies:
    - build amd64
  tags:
    - stackgres-runner
    - linux-amd64

build ui arm64:
  extends: .build ui
  dependencies:
    - build arm64
  tags:
    - stackgres-runner
    - linux-arm64
  only:
    variables:
      - $SKIP_ARM != "true" && $CI_COMMIT_TAG && $CI_COMMIT_TAG !~ /^latest-.*$/
      - $DO_ARM

build documentation:
  image: $CI_REGISTRY/$CI_PROJECT_PATH/$SG_CI_IMAGE_NAME
  stage: build 2
  tags:
    - stackgres-runner
  dependencies:
    - build amd64
  script:
    - |
      [ "$DEBUG" != true ] || set -x
      export DOCUMENTATION_BASE_URL="https://stackgres.io/doc"
      export DOCUMENTATION_EXTRA_PATH=""
      if [ -z "$CI_COMMIT_TAG" ] || echo "$CI_COMMIT_TAG" | grep -q '^latest-.*$'
      then
        DOCUMENTATION_BASE_URL="https://ongresinc.gitlab.io/stackgres"
        if [ "${CI_COMMIT_REF_NAME%%-*}" != "main" ] && [ "${CI_COMMIT_REF_NAME%%-*}" != "current" ]
        then
          DOCUMENTATION_EXTRA_PATH="$CI_COMMIT_REF_NAME/"
        fi
      fi
      sh stackgres-k8s/ci/build/build-gitlab.sh build \
        --extract documentation:doc/public \
        documentation
  retry: 2
  artifacts:
    expire_in: 1 week
    when: always
    paths:
    - doc/public

build helm packages:
  image: $CI_REGISTRY/$CI_PROJECT_PATH/$SG_CI_IMAGE_NAME
  stage: build 2
  tags:
    - stackgres-runner
  dependencies:
    - build amd64
  script:
    - |
      sh stackgres-k8s/ci/build/build-gitlab.sh build \
        --extract helm-packages:stackgres-k8s/install/helm/target/packages \
        helm-packages helm-operator-bundle helm-operator-openshift-bundle
  retry: 2
  artifacts:
    expire_in: 1 week
    when: always
    paths:
      - stackgres-k8s/install/helm/target/packages

build helm templates:
  image: $CI_REGISTRY/$CI_PROJECT_PATH/$SG_CI_IMAGE_NAME
  stage: build 2
  tags:
    - stackgres-runner
  dependencies:
    - build amd64
  script:
    - |
      sh stackgres-k8s/ci/build/build-gitlab.sh build \
        --extract helm-templates:stackgres-k8s/install/helm/target/templates \
        helm-templates
  retry: 2
  artifacts:
    expire_in: 1 week
    when: always
    paths:
      - stackgres-k8s/install/helm/target/templates

build helm release packages:
  image: $CI_REGISTRY/$CI_PROJECT_PATH/$SG_CI_IMAGE_NAME
  stage: build 2
  tags:
    - stackgres-runner
  dependencies:
    - build amd64
  script:
    - |
      sh stackgres-k8s/ci/build/build-gitlab.sh build \
        --extract helm-packages:stackgres-k8s/install/helm/target/packages \
        helm-release-packages helm-operator-release-bundle helm-operator-release-openshift-bundle
  retry: 2
  artifacts:
    expire_in: 1 week
    when: always
    paths:
      - stackgres-k8s/install/helm/target/packages

build helm release templates:
  image: $CI_REGISTRY/$CI_PROJECT_PATH/$SG_CI_IMAGE_NAME
  stage: build 2
  tags:
    - stackgres-runner
  dependencies:
    - build amd64
  script:
    - |
      sh stackgres-k8s/ci/build/build-gitlab.sh build \
        --extract helm-templates:stackgres-k8s/install/helm/target/templates \
        helm-release-templates
  retry: 2
  artifacts:
    expire_in: 1 week
    when: always
    paths:
      - stackgres-k8s/install/helm/target/templates
