apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sgconfigs.stackgres.io
spec:
  group: stackgres.io
  scope: Namespaced
  names:
    kind: SGConfig
    listKind: SGConfigList
    plural: sgconfigs
    singular: sgconfig
    shortNames:
      - sgopc
  versions:
    - name: v1
      served: true
      storage: true
      additionalPrinterColumns:
      - name: version
        type: string
        jsonPath: .status.version
      schema:
        openAPIV3Schema:
          type: object
          required: ["metadata", "spec"]
          properties:
            metadata:
              type: object
              properties:
                name:
                  type: string
                  maxLength: 63
                  pattern: "^[a-z]([-a-z0-9]*[a-z0-9])?$"
                  description: |
                    Name of the Operator Configuration. Only one configuration of the operator must exists. Following [Kubernetes naming conventions](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/architecture/identifiers.md), it must be an rfc1035/rfc1123 subdomain, that is, up to 253 characters consisting of one or more lowercase labels separated by `.`. Where each label is an alphanumeric (a-z, and 0-9) string, with a maximum length of 63 characters, with the `-` character allowed anywhere except the first or last character.
            spec:
              type: object
              "x-kubernetes-preserve-unknown-fields": true
              description: |
                The operator configuration spec. Please see https://stackgres.io/doc/latest/install/operator/parameters/
            status:
              type: object
              "x-kubernetes-preserve-unknown-fields": true
              description: |
                The operator configuration status.
