{{- if .Values.deploy.collector }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.collector.name }}-otelcol
  namespace: {{ .Release.Namespace }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
data:
  template-config.yaml: |
    extensions:
      health_check:
        endpoint: 0.0.0.0:13133
    {{- with .Values.collector.config.extensions }}
      {{- toYaml . | nindent 6 }}
    {{- end }}
    receivers:
      prometheus:
        config:
          scrape_configs:
    $(
    for CLUSTER_POD in ${CLUSTER_PODS}
    do
      cat << EOF
            - job_name: "${CLUSTER_POD%:*}-postgres"
              scrape_interval: 1m
              static_configs:
                - targets:
                  - "${CLUSTER_POD#*:}:9187"
            - job_name: "${CLUSTER_POD%:*}-envoy"
              scrape_interval: 1m
              metrics_path: /stats/prometheus
              static_configs:
                - targets:
                  - "${CLUSTER_POD#*:}:8001"
    EOF
    done
    )
    exporters:
    {{- with .Values.collector.config.exporters }}
      {{- toYaml . | nindent 6 }}
    {{- end }}
    service:
      telemetry:
        {{- with .Values.collector.config.service.telemetry }}
          {{- toYaml . | nindent 10 }}
        {{- end }}
      extensions:
        - health_check
      {{- with .Values.collector.config.service.extensions }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      pipelines:
        {{- with .Values.collector.config.service.pipelines }}
          {{- toYaml . | nindent 10 }}
        {{- end }}
  empty-config.yaml: |
    extensions:
      health_check:
        endpoint: 0.0.0.0:13133
    {{- with .Values.collector.config.extensions }}
      {{- toYaml . | nindent 6 }}
    {{- end }}
    receivers:
      prometheus:
        config:
          scrape_configs:
            - job_name: "dummy"
              scrape_interval: 1y
    exporters:
    {{- with .Values.collector.config.exporters }}
      {{- toYaml . | nindent 6 }}
    {{- end }}
    service:
      telemetry:
        {{- with .Values.collector.config.service.telemetry }}
          {{- toYaml . | nindent 10 }}
        {{- end }}
      extensions:
        - health_check
      {{- with .Values.collector.config.service.extensions }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      pipelines:
        {{- with .Values.collector.config.service.pipelines }}
          {{- toYaml . | nindent 10 }}
        {{- end }}
{{- end }}
