configurations:
  postgresconfig:
    postgresql.conf:
      shared_buffers: '32MB'
  objectstorage:
    create: true
    s3Compatible:
      bucket: restore-backup
      awsCredentials:
        secretKeySelectors:
          accessKeyId:
            name: restore-backup-minio
            key: accesskey
          secretAccessKey:
            name: restore-backup-minio
            key: secretkey
      region: k8s
      enablePathStyleAddressing: true
      endpoint: http://restore-backup-minio.restore-backup:9000
cluster:
  pods:
    persistentVolume:
      size: 128Mi
    managementPolicy: Parallel
  configurations:
    backups:
      cronSchedule: "0 5 31 2 *"
      sgObjectStorage: backupconf
nonProductionOptions:
  disableClusterPodAntiAffinity: true
